version: '3.8'

services:
  # Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-camera-backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - LOG_LEVEL=info
      - HOST=0.0.0.0
      - PORT=8000
      - FRONTEND_URL=http://localhost:8080
      - DEBUG=false
      - WORKERS=1
    volumes:
      - ./backend/logs:/app/logs
      - /tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-camera-network

  # Frontend Service (Nginx)
  frontend:
    image: nginx:alpine
    container_name: ai-camera-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ai-camera-network

volumes:
  nginx-logs:

networks:
  ai-camera-network:
    driver: bridge